name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: ./.github/actions/action-conan-install
    - run: ls -al .
    - run: cat /github/home/.conan/profiles/default
    - run: ctest --version
    - run: ctest -S .github.cmake -V
